trigger:
- kraken

name: 2.0.0$(Rev:.r)

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/pufferpanel/pufferpanel' # Path to the module's code
  version: $(Build.BuildNumber)

steps:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
      mkdir $(GOPATH)/build
      echo {} > $(GOPATH)/build/config.json
      go version
      sudo apt-get update
      sudo apt-get install gcc-arm-linux-gnueabihf
    displayName: 'Set up the Go workspace'

  - script: |
      curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      dep version
    workingDirectory: '$(modulePath)'
    displayName: 'Download dep'

  - script: |
      export GOOS=windows
      export GOARCH=amd64
      export CGO_ENABLED=1
      dep ensure -v
      go build -o $(GOPATH)/build/pufferpanel.exe -ldflags "-X github.com/pufferpanel/pufferpanel.Hash=$(Build.SourceVersion) -X github.com/pufferpanel/pufferpanel.Version=$(version)" -v github.com/pufferpanel/pufferpanel/cmd
    workingDirectory: '$(modulePath)'
    displayName: 'Windows Build'

  - script: |
      export GOOS=linux
      export GOARCH=amd64
      export CGO_ENABLED=1
      dep ensure -v
      go build -o $(GOPATH)/build/pufferpanel -ldflags "-X github.com/pufferpanel/pufferpanel.Hash=$(Build.SourceVersion) -X github.com/pufferpanel/pufferpanel.Version=$(version)" -v github.com/pufferpanel/pufferpanel/cmd
    workingDirectory: '$(modulePath)'
    displayName: 'Linux Build'

  - script: |
      export GOOS=linux
      export GOARCH=arm
      export CC=arm-linux-gnueabihf-gcc
      export CXX=arm-linux-gnueabihf-g++
      export CGO_ENABLED=1 
      export GOARM=7
      dep ensure -v
      go build -o $(GOPATH)/build/pufferpanel-arm -ldflags "-X github.com/pufferpanel/pufferpanel.Hash=$(Build.SourceVersion) -X github.com/pufferpanel/pufferpanel.Version=$(version)" -v github.com/pufferpanel/pufferpanel/cmd
    workingDirectory: '$(modulePath)'
    displayName: 'Linux Build - ARM'

  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.4'
      addToPath: true
    displayName: 'Install Ruby'

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '$(modulePath)/client'
    displayName: 'Install NPM'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: '$(modulePath)/client'
    displayName: 'NPM Build client files'

  - script: |
      mkdir -p $(GOPATH)/build/client/dist
      cp -r client/dist/* $(GOPATH)/build/client/dist
      cp -r assets $(GOPATH)/build/assets
    workingDirectory: '$(modulePath)'
    displayName: 'Copy assets'

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'pufferpanel/pufferpanel'
      command: 'buildAndPush'
      Dockerfile: '.azure/Dockerfile'
      buildContext: '$(GOPATH)/build'
      tags: 'kraken'

  - script: |
      git clone https://github.com/PufferPanel/systemd
    displayName: 'Get supporting files'
    workingDirectory: '$(modulePath)'

  - script: |
      gem install --no-doc rake
      gem install --no-doc fpm && fpm -v
      gem install --no-doc package_cloud && package_cloud version
    displayName: 'Install gem deps'

  - script: |
      fpm -s dir -t deb \
        --name pufferpanel -v $(version) \
        --maintainer dev@pufferpanel.com \
        --deb-user pufferpanel --deb-group pufferpanel \
        --deb-systemd servicefiles/systemd/pufferpanel \
        --before-install scripts/preinst.sh \
        --after-upgrade scripts/postupgrade.sh \
        --before-remove scripts/prerm.sh \
        --deb-after-purge scripts/purge.sh \
        $(GOPATH)/build/pufferpanel=/usr/sbin/pufferpanel \
        $(GOPATH)/build/client/dist=/var/www/pufferpanel/client/dist/ \
        $(GOPATH)/build/config.json=/etc/pufferpanel/config.json

      mkdir $(GOPATH)/build/xenial
      mv *.deb $(GOPATH)/build/xenial
    displayName: 'Create packages - xenial'
    workingDirectory: '$(modulePath)/systemd/pufferpanel/xenial'

  - script: |
      fpm -s deb -t rpm \
        --name pufferpanel \
        --maintainer dev@pufferpanel.com \
        --rpm-user pufferpanel --rpm-group pufferpanel \
        --before-install scripts/preinst.sh \
        --after-upgrade scripts/postupgrade.sh \
        --before-remove scripts/prerm.sh \
        $(GOPATH)/build/xenial/pufferpanel_*_amd64.deb

      mkdir $(GOPATH)/build/rpm
      mv *.rpm $(GOPATH)/build/rpm
    displayName: 'Create packages - rpm'
    workingDirectory: '$(modulePath)/systemd/pufferpanel/rpm7'

  - script: |
      fpm -s dir -t deb \
        --name pufferpanel -v $(version) \
        --maintainer dev@pufferpanel.com \
        --deb-user pufferpanel --deb-group pufferpanel \
        --deb-init servicefiles/initd/pufferpanel \
        --before-install scripts/preinst.sh \
        --before-remove scripts/prerm.sh \
        --deb-after-purge scripts/purge.sh \
        $(GOPATH)/build/pufferpanel=/usr/sbin/pufferpanel \
        $(GOPATH)/build/client/dist=/var/www/pufferpanel/client/dist/ \
        $(GOPATH)/build/config.json=/etc/pufferpanel/config.json

      mkdir $(GOPATH)/build/trusty
      mv *.deb $(GOPATH)/build/trusty
    displayName: 'Create packages - trusty'
    workingDirectory: '$(modulePath)/systemd/pufferpanel/trusty'

  - script: |
      fpm -s dir -t deb \
        --name pufferpanel -v $(version) \
        --maintainer dev@pufferpanel.com \
        --deb-user pufferpanel --deb-group pufferpanel \
        --deb-systemd servicefiles/systemd/pufferpanel \
        --before-install scripts/preinst.sh \
        --after-upgrade scripts/postupgrade.sh \
        --before-remove scripts/prerm.sh \
        --deb-after-purge scripts/purge.sh \
        -a armhf \
        $(GOPATH)/build/pufferpanel-arm=/usr/sbin/pufferpanel \
        $(GOPATH)/build/client/dist=/var/www/pufferpanel/client/dist/ \
        $(GOPATH)/build/config.json=/etc/pufferpanel/config.json

      mkdir $(GOPATH)/build/buster-arm
      mv *.deb $(GOPATH)/build/buster-arm
    displayName: 'Create packages - buster'
    workingDirectory: '$(modulePath)/systemd/pufferpanel/xenial'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'pufferpanel'
      targetPath: '$(GOPATH)/build/.'
    displayName: 'Publish'