trigger:
- kraken
- theme

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/pufferpanel/pufferpanel' # Path to the module's code
  version: 2.0.0

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    mkdir $(GOPATH)/build
    go version
  displayName: 'Set up the Go workspace'

- script: |
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    dep version
  workingDirectory: '$(modulePath)'
  displayName: 'Download dep'

- script: |
    export GOOS=windows
    dep ensure -v
    go build -o $(GOPATH)/build/pufferpanel.exe -v github.com/pufferpanel/pufferpanel
  workingDirectory: '$(modulePath)'
  displayName: 'Windows Build'

- script: |
    export GOOS=linux
    dep ensure -v
    rm -f *.syso
    go build -o $(GOPATH)/build/pufferpanel -v github.com/pufferpanel/pufferpanel
  workingDirectory: '$(modulePath)'
  displayName: 'Linux Build'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(modulePath)/client'
  displayName: 'NPM install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: '$(modulePath)/client'
  displayName: 'NPM Build client files'

- script: |
    mkdir -p $(GOPATH)/build/client/dist
    cp -r client/dist/* $(GOPATH)/build/client/dist
    cp -r assets $(GOPATH)/build/assets
  workingDirectory: '$(modulePath)'
  displayName: 'Copy assets'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'pufferpanel'
    targetPath: '$(GOPATH)/build/.'
