[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
   name = "github.com/pufferpanel/apufferi"
   branch = "master"

[prune]
  go-tests = true
  unused-packages = true