name: Go
on: 
  push:
    branches:
    - kraken
    
jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019]
        arch: [amd64, arm]
        go: [ '1.12' ]
        node-version: [ '12.x' ]
        exclude:
          - os: windows-2019
            arch: arm

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: pufferpanel
        
    - name: Pull deps
      uses: actions/checkout@v1
      with:
        repository: pufferpanel/apufferi
        path: apufferi
        ref: master
        
    - name: Build
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        echo replace github.com/pufferpanel/apufferi/v3 =\> ../apufferi >> go.mod
        go build -o pufferpanel -ldflags "-X github.com/pufferpanel/pufferpanel/version.Hash=${{ github.sha }}" -v github.com/pufferpanel/pufferpanel/v2/cmd
        
    - name: Build
      if: startsWith(matrix.os, 'windows')
      run: |
        echo replace github.com/pufferpanel/apufferi/v3 =^> ../apufferi >> go.mod
        go build -o pufferpanel.exe -ldflags "-X github.com/pufferpanel/pufferpanel/version.Hash=${{ github.sha }}" -v github.com/pufferpanel/pufferpanel/v2/cmd        

    - name: npm install, build
      run: |
        npm install
        npm run build
      env:
        CI: true
      working-directory: client
