name: Build
on: 
  push:
    branches:
    - kraken
    tags:
    - v2.*
    
jobs:
  skip:
    name: Skip build
    runs-on: [ubuntu-latest]
    if: "contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Skip
        run: |
          echo "Skipping build"
              
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    
    strategy:
      matrix:
        os: [ linux, windows ]
        arch: [ amd64, arm ]
        go: [ '1.13' ]
        exclude:
          - os: windows
            arch: arm

    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}

    steps:
    - name: Get the version
      run: echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}"
    
    - name: Get the version
      if: startsWith(env.VERSION, 'refs/')
      run: echo "::set-env name=VERSION::${GITHUB_REF/refs\/heads\//}"
      
    - name: Version
      run: |
        echo $VERSION
        echo $GITHUB_REF      

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: pufferpanel
        
    - name: Build
      if: startsWith(matrix.os, 'linux')
      run: |
        go build -o pufferpanel -ldflags "-X github.com/pufferpanel/pufferpanel/version.Hash=${{ github.sha }} -X github.com/pufferpanel/pufferpanel/version.Version=${{ env.VERSION }}" -v github.com/pufferpanel/pufferpanel/v2/cmd

    - name: Build
      if: startsWith(matrix.os, 'windows')
      run: |
        go build -o pufferpanel.exe -ldflags "-X github.com/pufferpanel/pufferpanel/version.Hash=${{ github.sha }} -X github.com/pufferpanel/pufferpanel/version.Version=${{ env.VERSION }}" -v github.com/pufferpanel/pufferpanel/v2/cmd

    - name: Rename
      if: startsWith(matrix.arch, 'arm')
      run: |
        mv pufferpanel pufferpanel_arm

    - name: Publish Binary
      uses: actions/upload-artifact@v1
      if: startsWith(matrix.os, 'linux') && startsWith(matrix.arch, 'amd')
      with:
        name: ${{ matrix.os }} ${{ matrix.arch }} - Binary
        path: pufferpanel

    - name: Publish Binary
      uses: actions/upload-artifact@v1
      if: startsWith(matrix.os, 'linux') && startsWith(matrix.arch, 'arm')
      with:
        name: ${{ matrix.os }} ${{ matrix.arch }} - Binary
        path: pufferpanel_arm

    - name: Publish Binary
      uses: actions/upload-artifact@v1
      if: startsWith(matrix.os, 'windows')
      with:
        name: ${{ matrix.os }} ${{ matrix.arch }} - Binary
        path: pufferpanel.exe

  produce-webartifacts:
    name: Generate web artifacts
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        node-version: [ '12.x' ]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          CI: true
        working-directory: client

      - name: Publish Supporting
        uses: actions/upload-artifact@v1
        with:
          name: Web Artifacts
          path: client/dist

  produce-packages:
    name: Generate packages artifacts
    runs-on: ubuntu-18.04
    needs: [produce-webartifacts,build-binaries]
        
    steps:
      - name: Get the version
        run: echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}"
    
      - name: Get the version
        if: startsWith(env.VERSION, 'refs/')
        run: echo "::set-env name=VERSION::${GITHUB_REF/refs\/heads\//}"      
      
      - uses: actions/setup-ruby@v1
        
      - name: Install gems
        run: |
          gem install --no-doc rake
          gem install --no-doc fpm && fpm -v
          gem install --no-doc package_cloud && package_cloud version
          
      - name: Pull deps
        uses: actions/checkout@v1
        with:
          repository: pufferpanel/systemd
          path: systemd
          ref: master
          
      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name: linux amd64 - Binary
          path: binaries
        
      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name: Web Artifacts
          path: client/dist
          
      - name: Build packages
        run: |
          echo { "web": { "files": "/var/www/pufferpanel/" } } > config.json

          fpm -s dir -t deb \
          --name pufferpanel -v ${{ env.VERSION }} \
          --maintainer dev@pufferpanel.com \
          --deb-user pufferpanel --deb-group pufferpanel \
          --deb-systemd ../systemd/pufferpanel/xenial/servicefiles/systemd/pufferpanel \
          --before-install ../systemd/pufferpanel/xenial/scripts/preinst.sh \
          --after-upgrade ../systemd/pufferpanel/xenial/scripts/postupgrade.sh \
          --before-remove ../systemd/pufferpanel/xenial/scripts/prerm.sh \
          --deb-after-purge ../systemd/pufferpanel/xenial/scripts/purge.sh \
          binaries/pufferpanel=/usr/sbin/pufferpanel \
          client/dist=/var/www/pufferpanel/ \
          config.json=/etc/pufferpanel/config.json
          
          mkdir -p build/xenial
          mv *.deb build/xenial

          fpm -s deb -t rpm \
          --name pufferpanel \
          --maintainer dev@pufferpanel.com \
          --rpm-user pufferpanel --rpm-group pufferpanel \
          --before-install ../systemd/pufferpanel/rpm7/scripts/preinst.sh \
          --after-upgrade ../systemd/pufferpanel/rpm7/scripts/postupgrade.sh \
          --before-remove ../systemd/pufferpanel/rpm7/scripts/prerm.sh \
          build/xenial/pufferpanel_*_amd64.deb

          mkdir -p build/rpm
          mv *.rpm build/rpm
          
          fpm -s dir -t deb \
          --name pufferpanel -v ${{ env.VERSION }} \
          --maintainer dev@pufferpanel.com \
          --deb-user pufferpanel --deb-group pufferpanel \
          --deb-init ../systemd/pufferpanel/trusty/servicefiles/initd/pufferpanel \
          --before-install ../systemd/pufferpanel/trusty/scripts/preinst.sh \
          --before-remove ../systemd/pufferpanel/trusty/scripts/prerm.sh \
          --deb-after-purge ../systemd/pufferpanel/trusty/scripts/purge.sh \
          binaries/pufferpanel=/usr/sbin/pufferpanel \
          client/dist=/var/www/pufferpanel/client/dist/ \
          config.json=/etc/pufferpanel/config.json

          mkdir -p build/trusty
          mv *.deb build/trusty
          
      - name: Publish Packages
        uses: actions/upload-artifact@v1
        with:
          name: Packages - RPM
          path: build/rpm/pufferpanel-${{ env.VERSION}}-1.x86_64.rpm

      - name: Publish Packages
        uses: actions/upload-artifact@v1
        with:
          name: Packages - Trusty DEB
          path: build/trusty/pufferpanel_${{ env.VERSION}}_amd64.deb

      - name: Publish Packages
        uses: actions/upload-artifact@v1
        with:
          name: Packages - Xenial DEB
          path: build/xenial/pufferpanel_${{ env.VERSION}}_amd64.deb

  release:
    if: startsWith(github.ref, 'v2.')
    runs-on: ubuntu-18.04
    name: Release project
    needs: [produce-packages]

    steps:
      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name: linux amd64 - Binary

      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name: windows amd64 - Binary

      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name: linux arm - Binary

      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name: Packages - RPM

      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name:  Packages - Trusty DEB
          path: trusty

      - name: Pull files
        uses: actions/download-artifact@v1
        with:
          name: Packages - Xenial DEB
          path: xenial

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pufferpanel
          asset_name: Linux amd64

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pufferpanel-arm
          asset_name: Linux arm

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pufferpanel_
          asset_name: Windows amd64

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pufferpanel.exe
          asset_name: Windows amd64

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./xenial/*
          asset_name: Xenial-compatible package

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./trusty/*
          asset_name: Trusty-compatible package

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.rpm
          asset_name: RPM package
